# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 10ccebee5e6bd5f6f5ee2cc6cffad5f60a7f65b5031fe9eef146fbdfd1ec283b017a81fc8c23c82925e1fd718fcb33cabbdc111b887757418f1f9be61c249ca0

test:
  secret_key_base: e8fc39b72b04e89c03647fd05a505353ebfbd5bfb46e66aeb37db4db6b87e4eadf52c92ff40d2525b034e85fe7bd8fdb387462232912289bc58fb7cda0068352

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
